# kiss_icp_ros/config/kiss_icp_params.yaml

kiss_icp_odometry:
  ros__parameters:
    # Frame Configuration
    base_frame: "base_link"
    odom_frame: "odom"
    lidar_frame: "velodyne"

    # Algorithm Parameters
    max_range: 100.0              # Maximum LiDAR range (meters)
    min_range: 1.0                # Minimum LiDAR range (meters)
    scan_duration: 0.1            # Expected scan duration (seconds)
    voxel_size: 0.5               # Voxel grid size for downsampling (meters)

    # ICP Parameters
    max_correspondences: 5000     # Maximum number of correspondences
    correspondence_threshold: 1.0  # Initial correspondence distance threshold
    max_icp_iterations: 50        # Maximum ICP iterations
    convergence_threshold: 0.001  # ICP convergence threshold

    # Adaptive Threshold Parameters
    use_adaptive_threshold: true  # Enable adaptive threshold
    initial_threshold: 2.0        # Initial threshold value
    min_threshold: 0.5           # Minimum threshold value
    max_threshold: 5.0           # Maximum threshold value

    # Motion Model Parameters
    use_constant_velocity: true   # Enable constant velocity model
    motion_compensation: true     # Enable motion compensation

    # Publishing Parameters
    publish_tf: true              # Publish TF transforms
    publish_path: true            # Publish trajectory path
    publish_local_map: true       # Publish local map
    publish_current_scan: true    # Publish current scan
    publish_deskewed_scan: false  # Publish deskewed scan

    # Path Parameters
    path_max_size: 1000          # Maximum number of poses in path

    # Quality Control
    min_motion_threshold: 0.01   # Minimum motion for processing (meters)
    max_angular_velocity: 2.0    # Maximum angular velocity (rad/s)
    max_linear_velocity: 10.0    # Maximum linear velocity (m/s)

kitti_player:
  ros__parameters:
    # Dataset Configuration
    dataset_path: "/path/to/kitti/dataset"
    sequence: "00"
    
    # Playback Configuration
    publish_rate: 10.0           # Publishing rate (Hz)
    frame_id: "velodyne"         # Point cloud frame ID
    loop_playback: true          # Enable loop playback
    auto_start: false            # Auto start playback

    # Data Processing
    skip_frames: 0               # Number of frames to skip
    max_points_per_scan: 150000  # Maximum points per scan